services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: classroom
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres-test:
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: classroom_test
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
